version: '3.7'

services:
  characterSheetsDb:
    image: "couchdb:latest"
    volumes:
      - "db_data:/opt/couchdb/data"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
    ports:
      - "5984:5984"
volumes:
  db_data:
